- name: Build your own playbook
  hosts: firewall01
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  vars:
    device_ip: '{{ device_ip }}'
    device_username: '{{ device_username }}'
    device_password: '{{ device_password }}'
    devicegroup: '{{ devicegroup }}'
    operation: 'add'


  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'panorama-secrets.yml'
    no_log: 'yes'

  - name: Task 1


  - name: Task 2


  - name: Task 3
