- name: Add some objects to the firewall
  hosts: vfirewalls
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Add an address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'lab03-address'
      address: '192.168.200.90/24'
      address_type: 'ip-netmask'
      description: 'This is a test address object'
      operation: 'add'

  - name: Add another address object to the firewall
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'lab03-address-group'
      address: '192.168.200.100-192.168.200.200'
      address_type: 'ip-range'
      description: 'This is a another test address object'
      operation: 'add'
