- name: Add some objects to Panorama
  hosts: panorama01
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'panorama-secrets.yml'
    no_log: 'yes'

  - name: Add an address object to Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'ps-address'
      address: '192.168.100.89/24'
      address_type: 'ip-netmask'
      description: 'This is a test address object'
      devicegroup: 'shared_services_11022'
      operation: 'add'

  - name: Add another address object to Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'ps-range'
      address: '192.168.100.100-192.168.100.200'
      address_type: 'ip-range'
      description: 'This is a another test address object'
      devicegroup: 'shared_services_11022'
      operation: 'add'

  - name: Add an address group to Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressgroup: 'ps-address-group'
      static_value: ['ps-address','ps-range']
      description: 'This is a test addressgroup'
      devicegroup: 'shared_services_11022'
      operation: 'add'

  - name: Add a service to Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      serviceobject: 'service--ps-01'
      protocol: 'tcp'
      destination_port: '8889'
      description: 'This is a test service object'
      devicegroup: 'shared_services_11022'
      operation: 'add'

  - name: Add another service to Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      serviceobject: 'service--ps-01'
      protocol: 'tcp'
      destination_port: '5000,5001,6000-7000'
      description: 'This is a test service object'
      devicegroup: 'shared_services_11022'
      operation: 'add'

  - name: Add a service group to Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      servicegroup: 'ps-service-group'
      services: ['service-abc','service-xyz']
      description: 'This is a test servicegroup'
      devicegroup: 'shared_services_11022'
      operation: 'add'

  
