- name: Set basic FW mgmt config
  hosts: firewall01
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Load basic mgmt. config
    include_vars: 'firewall-mgmt.yml'

  - name: set dns, ntp, and panorama and commit
    panos_mgtconfig:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
      dns_server_primary: "{{ dns_server_primary }}"
      dns_server_secondary: "{{ dns_server_secondary }}"
      panorama_primary: "{{ panorama_primary }}"
      panorama_secondary: "{{ panorama_secondary }}"
      ntp_server_primary: "{{ ntp_server_primary }}"
      ntp_server_secondary: "{{ ntp_server_secondary }}"
      timezone: "{{ timezone }}"
      update_server: "{{ update_server }}"
      login_banner: "{{ login_banner }}"
      commit: True
