---

- name: Update Panorama Template
  vars:
    device_sn: "{{ sn }}"
  vss_pan_template:
    ip_address: '{{ ip_address }}'
    username: '{{ username }}'
    password: '{{ password }}'
    api_key: '{{ api_key }}'
    device_serial: '{{ sn }}'
  register: new_devices
- debug: var=new_devices.meta
