---
- debug: msg="Step 1- Installing apps and threat contents for {{ sn }}"
- name: Update Apps and Threat Contents
  vars:
    device_sn: "{{ sn }}"
  vss_pan_contents_update:
    ip_address: '{{ ip_address }}'
    username: '{{ username }}'
    password: '{{ password }}'
    api_key: '{{ api_key }}'
    device_serial: '{{ sn }}'
  register: apps_up_status
- debug: var=apps_up_status.meta.retval

- debug: msg="Step 2- Installing AV contents for {{ sn }}"
- name: Update AV Contents
  vars:
    device_sn: "{{ sn }}"
  vss_pan_av_update:
    ip_address: '{{ ip_address }}'
    username: '{{ username }}'
    password: '{{ password }}'
    api_key: '{{ api_key }}'
    device_serial: '{{ sn }}'
  register: av_up_status
  when: apps_up_status.meta.retval=="Contents installed successfully"
- debug: var=av_up_status.meta.retval

- debug: msg="Step 3- Attach Template stack and Device group for {{ sn }}"
- name: Update Panorama Templates and Device groups
  vars:
    device_sn: "{{ sn }}"
  vss_pan_add_tmpl_dg:
    ip_address: '{{ ip_address }}'
    username: '{{ username }}'
    password: '{{ password }}'
    api_key: '{{ api_key }}'
    device_serial: '{{ sn }}'
  register: tmpl_dg_result
  when: apps_up_status.meta.retval=="Contents installed successfully"
- debug: var=tmpl_dg_result.meta.retval

- debug: msg="Step 4- Commit configuration for  {{ sn }}"
- name: Committing configuration
  vars:
    device_sn: "{{ sn }}"
  vss_pan_commit:
    ip_address: '{{ ip_address }}'
    username: '{{ username }}'
    password: '{{ password }}'
    api_key: '{{ api_key }}'
    device_serial: '{{ sn }}'
    template: '{{ tmpl_dg_result.meta.template }}'
    device_group: '{{ tmpl_dg_result.meta.DG }}'
  register: commit_result
  when: tmpl_dg_result.meta.retval=="Template and DG added successfully"
- debug: var=commit_result.meta.retval

- debug: msg="Step 5- Install software for  {{ sn }}"
- name: Update PAN-OS
  vars:
    device_sn: "{{ sn }}"
  vss_pan_os_update:
    ip_address: '{{ ip_address }}'
    username: '{{ username }}'
    password: '{{ password }}'
    api_key: '{{ api_key }}'
    device_serial: '{{ sn }}'
  register: pan_os_result
  when: commit_result.meta.retval=="Successfully committed both template and device group"
- debug: var=pan_os_result.meta.retval
